### PR TITLE
Use requests built-in funcitonality to retry requests

### PR DESCRIPTION
**Pull request by beastie29a**
While testing the home assistant integration I began to get several 429 responses from the homeconnect API and eventually was blocked for several hours. I noticed the API server included the Retry-After header so thought it would make sense to setup the retry logic built into the requests package.

429 with Retry-After in the header
```
send: b'GET /api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/status HTTP/1.1\r\nHost: simulator.home-connect.com\r\n...
reply: 'HTTP/1.1 429 Too Many Requests\r\n'
header: Date: Wed, 07 Feb 2024 19:15:08 GMT
header: Content-Type: application/vnd.bsh.sdk.v1+json
header: Content-Length: 181
header: Connection: keep-alive
header: Vary: Origin
header: Retry-After: 4
```
Retry after 4 seconds
```
send: b'GET /api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/status HTTP/1.1\r\nHost: simulator.home-connect.com\r\n...
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 07 Feb 2024 19:15:13 GMT
header: Content-Type: application/vnd.bsh.sdk.v1+json
header: Content-Length: 484
header: Connection: keep-alive
header: Vary: Origin
```

### CODE REVIEW

**Comment by christian1986** [comment]
What's stopping the merge?

**Review by christian1986 — APPROVED** [review]

**Comment by DavidMStraub** [comment]
Apologies, will review & merge very soon.

**Comment by christian1986** [comment]
How soon😅?

**Comment by DavidMStraub** [comment]
Sorry for the delay. Can you please do me a favour and confirm that you have tested this to work also with the new v2.0.0 release of `requests_oauthlib`? I can't test it right now unfortunately.

**Comment by beastie29a** [comment]
> Sorry for the delay. Can you please do me a favour and confirm that you have tested this to work also with the new v2.0.0 release of `requests_oauthlib`? I can't test it right now unfortunately.

No worries. I added some unit tests in the last commit and did some integration testing with Home Assistant (which had v2.0.0 of `requests_oauthlib`:
```
>>> import requests_oauthlib
>>> requests_oauthlib.__version__
'2.0.0'
```
urllib3 debug logs:
```
2024-06-26 17:33:11.672 DEBUG (SyncWorker_4) [urllib3.connectionpool] https://simulator.home-connect.com:443 "GET /api/homeappliances/BOSCH-HCS01OVN1-43E0065FE245/programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeating HTTP/1.1" 429 182
2024-06-26 17:33:11.673 DEBUG (SyncWorker_4) [urllib3.util.retry] Incremented Retry for (url='/api/homeappliances/BOSCH-HCS01OVN1-43E0065FE245/programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeating'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2024-06-26 17:33:44.674 DEBUG (SyncWorker_4) [urllib3.connectionpool] Retry: /api/homeappliances/BOSCH-HCS01OVN1-43E0065FE245/programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeating
2024-06-26 17:33:44.866 DEBUG (SyncWorker_4) [urllib3.connectionpool] https://simulator.home-connect.com:443 "GET /api/homeappliances/BOSCH-HCS01OVN1-43E0065FE245/programs/available/Cooking.Oven.Program.HeatingMode.TopBottomHeating HTTP/1.1" 200 518

2024-06-26 17:34:14.413 DEBUG (SyncWorker_3) [urllib3.connectionpool] https://simulator.home-connect.com:443 "GET /api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/status/BSH.Common.Status.DoorState HTTP/1.1" 429 182
2024-06-26 17:34:14.413 DEBUG (SyncWorker_3) [urllib3.util.retry] Incremented Retry for (url='/api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/status/BSH.Common.Status.DoorState'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2024-06-26 17:34:45.414 DEBUG (SyncWorker_3) [urllib3.connectionpool] Retry: /api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/status/BSH.Common.Status.DoorState
2024-06-26 17:34:45.606 DEBUG (SyncWorker_3) [urllib3.connectionpool] https://simulator.home-connect.com:443 "GET /api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/status/BSH.Common.Status.DoorState HTTP/1.1" 200 113A
```
Also saw this exception so added a handler for it since I didn't know if I should leave:
```
2024-06-26 19:13:36.399 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472438265760] Unexpected exception
Traceback (most recent call last):
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 896, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 886, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='simulator.home-connect.com', port=443): Max retries exceeded with url: /api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/programs/active (Caused by ResponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/core/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/core.py", line 2728, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/workspaces/core/homeassistant/core.py", line 2771, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/workspaces/core/homeassistant/components/home_connect/switch.py", line 67, in async_turn_on
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/homeconnect/api.py", line 368, in start_program
    return self.put("/programs/active", {"data": {"key": program_key}})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/homeconnect/api.py", line 333, in put
    return self.hc.put(
           ^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/homeconnect/api.py", line 106, in put
    res = self.request(
          ^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/homeconnect/api.py", line 82, in request
    return getattr(self._oauth, method)(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/requests_oauthlib/oauth2_session.py", line 566, in request
    return super(OAuth2Session, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/ha-venv/lib/python3.12/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='simulator.home-connect.com', port=443): Max retries exceeded with url: /api/homeappliances/SIEMENS-HCS03WCH1-7BC6383CF794/programs/active (Caused by ResponseError('too many 429 error responses'))
```

**Pull request merged**
